FUNCTION(CHAR_HEX_TO_DEC val out)
   STRING(TOUPPER ${val} val)
   IF(val STREQUAL A)
      SET(${out} 10 PARENT_SCOPE)
   ELSEIF(val STREQUAL B)
      SET(${out} 11 PARENT_SCOPE)
   ELSEIF(val STREQUAL C)
      SET(${out} 12 PARENT_SCOPE)
   ELSEIF(val STREQUAL D)
      SET(${out} 13 PARENT_SCOPE)
   ELSEIF(val STREQUAL E)
      SET(${out} 14 PARENT_SCOPE)
   ELSEIF(val STREQUAL F)
      SET(${out} 15 PARENT_SCOPE)
   ELSE()
      SET(${out} ${val} PARENT_SCOPE)
   ENDIF()
ENDFUNCTION(CHAR_HEX_TO_DEC)

FUNCTION(CHAR_DEC_TO_HEX val out)
   STRING(TOUPPER ${val} val)
   IF(val STREQUAL 10)
      SET(${out} A PARENT_SCOPE)
   ELSEIF(val STREQUAL 11)
      SET(${out} B PARENT_SCOPE)
   ELSEIF(val STREQUAL 12)
      SET(${out} C PARENT_SCOPE)
   ELSEIF(val STREQUAL 13)
      SET(${out} D PARENT_SCOPE)
   ELSEIF(val STREQUAL 14)
      SET(${out} E PARENT_SCOPE)
   ELSEIF(val STREQUAL 15)
      SET(${out} F PARENT_SCOPE)
   ELSE()
      SET(${out} ${val} PARENT_SCOPE)
   ENDIF()
ENDFUNCTION(CHAR_DEC_TO_HEX)

FUNCTION(CONVERT_TODEC out) # args: out [val]
   IF(${ARGC} EQUAL 2)
      SET(TMP_VAL ${ARGV1})
      IF(TMP_VAL MATCHES "^0[xX][0-9a-fA-F]+$")
         SET(TMPOUT 0)
         SET(TMPS 2)
         STRING(LENGTH ${TMP_VAL} TMPE)
         MATH(EXPR TMPE "${TMPE} - 1")
         FOREACH(I RANGE ${TMPS} ${TMPE})
            STRING(SUBSTRING ${TMP_VAL} ${I} 1 TMP_CH)
            CHAR_HEX_TO_DEC(${TMP_CH} TMP_CH)
            MATH(EXPR TMPOUT "${TMPOUT} * 16 + ${TMP_CH}")
         ENDFOREACH(I)
         SET(${out} ${TMPOUT} PARENT_SCOPE)
      ELSE()
         SET(${out} ${TMP_VAL} PARENT_SCOPE)
      ENDIF()
   ELSEIF(${ARGC} EQUAL 1)
      CONVERT_TODEC(${out} ${${out}})
      SET(${out} ${${out}} PARENT_SCOPE)
   ELSE()
      MESSAGE(FATAL_ERROR "Wrong arguments to CONVERT_TOHEX")
   ENDIF()
ENDFUNCTION(CONVERT_TODEC)

FUNCTION(CONVERT_TOHEX out)  # args: out [val]
   IF(${ARGC} EQUAL 2)
      SET(TMP_VAL ${ARGV1})
      IF(TMP_VAL MATCHES "^[0-9]+$")
         IF(TMP_VAL EQUAL 0)
            SET(TMPOUT "0")
         ELSE()
            SET(TMPOUT "")
            WHILE(TMP_VAL GREATER 0)
               MATH(EXPR TMP_CH "${TMP_VAL} % 16")
               CHAR_DEC_TO_HEX(${TMP_CH} TMP_CH)
               SET(TMPOUT "${TMP_CH}${TMPOUT}")
               MATH(EXPR TMP_VAL "${TMP_VAL} / 16")
            ENDWHILE()
         ENDIF()
         SET(${out} "0x${TMPOUT}" PARENT_SCOPE)
      ELSE()
         SET(${out} ${TMP_VAL} PARENT_SCOPE)
      ENDIF()
   ELSEIF(${ARGC} EQUAL 1)
      CONVERT_TOHEX(${out} ${${out}})
      SET(${out} ${${out}} PARENT_SCOPE)
   ELSE()
      MESSAGE(FATAL_ERROR "Wrong arguments to CONVERT_TOHEX")
   ENDIF()
ENDFUNCTION(CONVERT_TOHEX)

#
# Converts given memory size (ex. 64K, 1M, 0x20K, etc) to
# hexadecimal bytes value (ex. 0x10000, 0x100000, 0x8000).
#
FUNCTION(STM32_MEMSIZE_TO_HEX_BYTES MS BYTES)
    STRING(REGEX REPLACE "^(.+)[kK]$" "\\1" KILOBYTES ${MS})
    STRING(REGEX REPLACE "^(.+)[mM]$" "\\1" MEGABYTES ${MS})
    IF(KILOBYTES)
        CONVERT_TODEC(CALC_TMP ${KILOBYTES})
        MATH(EXPR CALC_TMP "${CALC_TMP} * 4")
        CONVERT_TOHEX(CALC_TMP)
        SET(${BYTES} "${CALC_TMP}00" PARENT_SCOPE)
    ELSEIF(MEGABYTES)
        CONVERT_TOHEX(CALC_TMP ${MEGABYTES})
        SET(${BYTES} "${CALC_TMP}00000" PARENT_SCOPE)
    ELSE()
        CONVERT_TOHEX(${BYTES} ${MS})
        SET(${BYTES} ${${BYTES}} PARENT_SCOPE)
    ENDIF()
ENDFUNCTION()
